# Generated by Django 5.2.6 on 2026-03-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsite',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
