# Generated by Django 5.2.6 on 2026-03-25 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_userwebsite_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userwebsite',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwebsite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
