# Generated by Django 5.2.6 on 2026-03-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_userwebsite_created_at_userwebsite_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsite',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userwebsite',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
