# Generated by Django 5.2.6 on 2026-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_userwebsite_deleted_at_userwebsite_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwebsite',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
