# Generated by Django 5.2.6 on 2026-01-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_certificate_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('bachelor', 'Bakalavr'), ('master', 'Magistr'), ('doctorate', 'Doktorantura'), ('secondary', 'Orta'), ('full_secondary', 'Tam orta'), ('vocational', 'Peşə təhsili'), ('certification', 'Təhsil Artırma/Sertifikat')], db_index=True, max_length=20),
        ),
    ]
