# Generated by Django 5.2.6 on 2026-01-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
