# Generated by Django 5.2.6 on 2026-01-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_bookingrequest_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
