# Generated by Django 5.2.6 on 2026-03-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_bookingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='meet_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
