# Generated by Django 5.2.6 on 2026-03-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_bookingrequest_location_bookingrequest_meet_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
