# Generated by Django 5.2.6 on 2026-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_surveyresponse_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, default='az', max_length=2),
        ),
    ]
