# Generated by Django 5.2.6 on 2026-01-01 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_choice', models.CharField(max_length=50)),
                ('settings_json', models.JSONField(default=dict)),
                ('custom_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='company_qrs/')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_config', to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='UserWebsiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_choice', models.CharField(max_length=50)),
                ('settings_json', models.JSONField(default=dict)),
                ('qr_code', models.ImageField(blank=True, upload_to='user_qrs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
