# Generated by Django 5.2.6 on 2026-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
