# Generated by Django 5.2.6 on 2026-01-25 16:13

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_searchable_user_notify_email_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='open_to',
            field=models.JSONField(blank=True, default=apps.accounts.models.User.default_open_to),
        ),
    ]
