# Generated by Django 5.2.6 on 2026-03-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_open_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
