# Generated by Django 5.2.6 on 2026-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_az',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='name_az',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='profession',
            new_name='profession_az',
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='profession_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='profession_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
