# Generated by Django 5.2.6 on 2026-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_vacancy_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
