# Generated by Django 5.2.6 on 2026-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_vacancy_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
