# Generated by Django 5.2.6 on 2026-01-17 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourvalues',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='our_values', to='business.company'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='what_we_do', to='business.company'),
        ),
        migrations.AlterField(
            model_name='whoweare',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='who_we_are', to='business.company'),
        ),
    ]
