# Generated by Django 5.2.6 on 2026-01-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_alter_ourvalues_company_alter_whatwedo_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_covers/'),
        ),
    ]
