# Generated by Django 5.2.6 on 2026-03-27 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_company_company_size_alter_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='language',
            field=models.CharField(choices=[('az', 'Azerbaijani'), ('en', 'English'), ('ru', 'Russian')], db_index=True, default='az', max_length=2),
        ),
    ]
